export const GET_ACCOUNTS = 'GET_EXPENSES';
export const GET_ACCOUNTS_COUNT = 'GET_EXPENSES_COUNT';
export const CLEAR_ACCOUNTS = 'CLEAR_ACCOUNTS';
export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
