export const GET_EXPENSES = 'GET_EXPENSES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CLEAR_EXPENSES = 'CLEAR_EXPENSES';
export const GET_EXPENSES_COUNT = 'GET_EXPENSES_COUNT';
export const GET_ACCOUNT = 'GET_ACCOUNT';
